language: bash

services:
  - docker

before_install:
  - docker build -t chirage/mosquittoauthplugin:1.6.8 .
  - docker run -d chirage/mosquittoauthplugin:1.6.8
  - docker ps -a

deploy:
  provider: script
  srcipt: bash docker_push
  on:
    branch: master