version: "3"

services:
  mqtt:
    build: .
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    expose:
      - 1883
    ports:
      - "1883:1883"
    networks:
      - mongo-backend
    environment:
      - DOMAIN=example.local
      - PORT=8080
    tty: true
    stdin_open: true

  mongo:
    build: ./mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mongo-backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mqtt
      MONGO_INITDB_DATABASE: mqGate
    volumes:
      - mongodata:/data/db
  
  mongo-express:
    image: mongo-express
    restart: always
    depends_on: 
      - mongo
    ports:
      - "8084:8081"
    networks: 
      - mongo-backend
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mqtt
      ME_CONFIG_MONGODB_SERVER: 'mongo'

networks:
  mongo-backend:

volumes:
  mongodata:
